server:
  port: 8082

spring:
  application:
    name: history-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/test

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
