server:
  port: ${PORT}

spring:
  application:
    name: history-service
  data:
    mongodb:
      uri: mongodb://${DATABASE_URL}/${DATABASE_SCHEMA}

  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: test-consumer-group
