version: 1.0.0
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    logging:
      driver: none
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    logging:
      driver: none
    networks:
      - my-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    networks:
      - my-network

  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=leafall
    volumes:
      - ./scripts/postgre:/docker-entrypoint-initdb.d
    networks:
      - my-network

  history-service:
    image: starleken/history-service
    depends_on:
      - mongodb
      - kafka
    environment:
      - PORT=8082
      - DATABASE_URL=mongodb
      - DATABASE_SCHEMA=test
      - KAFKA_URL=kafka:9092
    ports:
      - '8082:8082'
    networks:
      - my-network

  file-service:
    image: starleken/file-service
    depends_on:
      - postgres
      - history-service
    environment:
      - PORT=8081
      - DB_URL=postgres:5432
      - DB_SCHEMA=leafall_files
      - DB_USERNAME=postgres
      - DB_PASSWORD=1111
      - BUCKET_NAME=leafall
      - KAFKA_URL=kafka:9092
    ports:
      - '8081:8081'
    networks:
      - my-network

  auth-service:
    image: starleken/auth-service
    depends_on:
      - postgres
      - history-service
    environment:
      - PORT=8084
      - DB_URL=postgres:5432
      - DB_SCHEMA=leafall_auth
      - DB_USERNAME=postgres
      - DB_PASSWORD=1111
      - KAFKA_URL=kafka:9092
    ports:
      - '8084:8084'
    networks:
      - my-network

  main-service:
    image: starleken/main-service
    depends_on:
      - postgres
      - history-service
      - file-service
    environment:
      - PORT=8080
      - DB_URL=postgres:5432
      - DB_SCHEMA=leafall
      - DB_USERNAME=postgres
      - DB_PASSWORD=1111
      - FILE_SERVICE_URL=http://file-service:8081
      - KAFKA_URL=kafka:9092
    ports:
      - '8080:8080'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge