server:
  port: ${PORT}

spring:
  application:
    name: file-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml

aws:
  s3:
    bucket-name: ${BUCKET_NAME}
    presigned-url-ttl-millis: 1800000